---
- name: install packages
  apt: name={{ item }} state=present
  with_items:
        - nginx
        - python-virtualenv
        - python-dev
        - build-essential
        - supervisor
        - git-core

