# Defines our Vagrant environment
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  #vbguest
  config.vbguest.auto_update = false
  config.vbguest.no_remote = true
  
  #start bash as a non-login shell (fix 'stdin: is not a tty' error)
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  
  #vagrant plugin to install run command 'vagrant plugin install vagrant-hostmanager'
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true
  
  config.ssh.insert_key = false

  #load balancer
  config.vm.define :balancer do |balancer_config|
      balancer_config.vm.box = "ubuntu/trusty64"
      balancer_config.vm.hostname = "balancer"
      balancer_config.vm.network :private_network, ip: "192.168.55.10"
      balancer_config.vm.network "forwarded_port", guest: 8080, host: 8080
      balancer_config.vm.provider "virtualbox" do |vb|
        vb.memory = "256"
      end
  end
 
  #MongoDB
  config.vm.define :mongodb do |mongodb_config|
      mongodb_config.vm.box = "ubuntu/trusty64"
      mongodb_config.vm.hostname = "mongodb"
      mongodb_config.vm.network :private_network, ip: "192.168.55.20"
      mongodb_config.vm.network "forwarded_port", guest: 27017, host: 27017
      mongodb_config.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
      end
  end
  
  #microservice app  instance
  N=2 #web servers number
  (1..N).each do |i|
    config.vm.define "app#{i}" do |node|
        node.vm.box = "ubuntu/trusty64"
        node.vm.hostname = "app#{i}"
        node.vm.network :private_network, ip: "192.168.55.10#{i}"
        node.vm.network "forwarded_port", guest: 8081, host: "808#{i}"
        node.vm.provider "virtualbox" do |vb|
          vb.memory = "256"
        end
    # Execute  ansible provisioner once,
    # when all the machines are up and ready.
       if i == N
         node.vm.provision :hostmanager
         node.vm.provision :ansible do |ansible|
           # Disable default limit to connect to all the machines
           #ansible.sudo = true
           ansible.limit = "all"
           ansible.inventory_path ="ansible/hosts"
           ansible.playbook = "ansible/playbooks/site.yml"
           #ansible.verbose =  'vvvv'
         end
       end

    end
  end

end
